--DB NAME: sfsystem
--username: sfadmin
--password: sfadmin

create table USERS
(
	USER_ID INTEGER CONSTRAINT user_pk primary key GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	ULID VARCHAR(32),
	PASSWORD VARCHAR(32),
	ISADMIN INTEGER,
	CREATED_TS TIMESTAMP,
	LAST_UPDT_TS TIMESTAMP
);

create table REVIEW_COMMENT
(
	COMMENT_ID INTEGER CONSTRAINT review_comment_pk primary key GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	ULID VARCHAR(32),
	ALL_SCH_ID INTEGER,
	COMMENT_TEXT VARCHAR(3000),
	CREATED_TS TIMESTAMP,
	LAST_UPDT_TS TIMESTAMP	
);


create table ALL_SCHEDULE
(
	ALL_SCH_ID INTEGER CONSTRAINT all_schedule_pk primary key GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	SCHEDULE_NAME VARCHAR(100),
	DESCRIPTION VARCHAR(255),
	CREATED_TS TIMESTAMP,
	LAST_UPDT_TS TIMESTAMP
);

create table TO_DO
(
	TO_DO_ID INTEGER CONSTRAINT to_do_pk primary key GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	ULID VARCHAR(32),
	ALL_SCH_ID INTEGER,
	STATUS INTEGER,
	CREATED_TS TIMESTAMP,
	LAST_UPDT_TS TIMESTAMP
 );

create table COURSE_SECTION
(
	SECTION_ID INTEGER CONSTRAINT section_pk primary key GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	COURSE_ID INTEGER,
	ALL_SCH_ID INTEGER,
	SECTION_NUMBER VARCHAR(32),
	CREATED_TS TIMESTAMP,
	LAST_UPDT_TS TIMESTAMP
);

CREATE TABLE PROFESSOR
(
        PROF_ID INTEGER CONSTRAINT professor_pk primary key GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
        PROF_NAME varchar(100),
        ULID varchar(100),
        EMPLOYMENT_STATUS INTEGER,
        TEACHING_STATUS INTEGER,
        CREATED_TS TIMESTAMP ,
        LAST_UPDT_TS TIMESTAMP 
);

CREATE TABLE ROOM
(
        ROOM_ID INTEGER CONSTRAINT room_pk primary key GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
        ROOM_NAME varchar(100),
        IS_LAB INTEGER,
        IS_AVAILABLE INTEGER,
        CREATED_TS TIMESTAMP ,
        LAST_UPDT_TS TIMESTAMP 
);

CREATE TABLE COURSE
(
        COURSE_ID INTEGER CONSTRAINT course_pk primary key GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
        COURSE_CODE varchar(100),
        COURSE_NAME varchar(100),
        CREATED_TS TIMESTAMP ,
        LAST_UPDT_TS TIMESTAMP 
);

CREATE TABLE SCHEDULE
(
        SCHEDULE_ID INTEGER CONSTRAINT schedule_pk primary key GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
        ALL_SCH_ID INTEGER,
        SECTION_ID INTEGER,
        PROF_ID INTEGER,
        ROOM_ID INTEGER,
        DAYS varchar(100),
        CLASS_TIME varchar(100),
        CREATED_TS TIMESTAMP ,
        LAST_UPDT_TS TIMESTAMP 
);

CREATE TABLE COURSE_PREFERENCE
(
	COURSE_PREFERENCE_ID INTEGER CONSTRAINT course_pref_pk primary key GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	PROF_ID INTEGER,
	COURSE_ID INTEGER,
	LAB_NEEDED INTEGER,
    INTEREST_LEVEL INTEGER,
	COURSE_COMMENTS VARCHAR(3000),
	CREATED_TS TIMESTAMP,
	LAST_UPDT_TS TIMESTAMP
);

CREATE TABLE DAY_PREFERENCE
(
	DAY_PREFERENCE_ID INTEGER CONSTRAINT day_pref_pk primary key GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	PROF_ID INTEGER,
	DAYS VARCHAR(100),
	PREFERRED_TIME VARCHAR(100),
	FINAL_COMMENTS VARCHAR(3000),
	OTHER_INTERESTS VARCHAR(3000),
	CREATED_TS TIMESTAMP,
	LAST_UPDT_TS TIMESTAMP
);

--POPULATE ROOM TABLE
INSERT INTO SFADMIN.ROOM (ROOM_NAME, IS_LAB, IS_AVAILABLE, CREATED_TS, LAST_UPDT_TS) VALUES ('CVA 151', 0, 1, CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO SFADMIN.ROOM (ROOM_NAME, IS_LAB, IS_AVAILABLE, CREATED_TS, LAST_UPDT_TS) VALUES ('OU 132', 1, 1, CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO SFADMIN.ROOM (ROOM_NAME, IS_LAB, IS_AVAILABLE, CREATED_TS, LAST_UPDT_TS) VALUES ('OU 133', 1, 1, CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO SFADMIN.ROOM (ROOM_NAME, IS_LAB, IS_AVAILABLE, CREATED_TS, LAST_UPDT_TS) VALUES ('OU 213D', 1, 1, CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO SFADMIN.ROOM (ROOM_NAME, IS_LAB, IS_AVAILABLE, CREATED_TS, LAST_UPDT_TS) VALUES ('OU 213E', 1, 1, CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO SFADMIN.ROOM (ROOM_NAME, IS_LAB, IS_AVAILABLE, CREATED_TS, LAST_UPDT_TS) VALUES ('STV 101', 0, 1, CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO SFADMIN.ROOM (ROOM_NAME, IS_LAB, IS_AVAILABLE, CREATED_TS, LAST_UPDT_TS) VALUES ('STV 104', 0, 1, CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO SFADMIN.ROOM (ROOM_NAME, IS_LAB, IS_AVAILABLE, CREATED_TS, LAST_UPDT_TS) VALUES ('STV 105', 0, 1, CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO SFADMIN.ROOM (ROOM_NAME, IS_LAB, IS_AVAILABLE, CREATED_TS, LAST_UPDT_TS) VALUES ('STV 108', 0, 1, CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO SFADMIN.ROOM (ROOM_NAME, IS_LAB, IS_AVAILABLE, CREATED_TS, LAST_UPDT_TS) VALUES ('STV 139A', 0, 1, CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO SFADMIN.ROOM (ROOM_NAME, IS_LAB, IS_AVAILABLE, CREATED_TS, LAST_UPDT_TS) VALUES ('WIH 123', 0, 1, CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO SFADMIN.ROOM (ROOM_NAME, IS_LAB, IS_AVAILABLE, CREATED_TS, LAST_UPDT_TS) VALUES ('ONLINE', 0, 1, CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO SFADMIN.ROOM (ROOM_NAME, IS_LAB, IS_AVAILABLE, CREATED_TS, LAST_UPDT_TS) VALUES ('TBD', 0, 1, CURRENT TIMESTAMP, CURRENT TIMESTAMP);

--POPULATE COURSE TABLE
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 115',  'Reasoning about Complex Systems', CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 140',  'Interacting in a Digital World',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 150', 'Using Microcomputer Productivity Tools',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 164',   'Introduction to Problem Solving Using the Computer',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 165',   'Computer Programming for Scientists',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 214'   ,'Social, Legal, and Ethical Issues in Information Technology',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 390',   'Methodologies for Teaching Computer Science',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 168',   'Structured Problem-Solving Using the Computer',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 178',   'Computer Application Programming',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 179',   'Introduction to Data Structures',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 191',   'Introduction to IT Professional Practice',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 225',   'Computer Organization',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 226',   'Advanced Practical Application Development',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 254',   'Hardware and Software Concepts',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 261',   'Systems Development I',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 262',   'Information Technology Project Management',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 275',   'Java as a 2nd Language',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 272',   'COBOL as a 2nd Language',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 279',   'Algorithms and Data Structures',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 326',   'Principles of Software Engineering',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 327',   'Concepts of Programming Languages',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 328',   'Introduction to Theory of Computation',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 330',   'Introduction to Enterprise Systems (ES) Computing',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 332',   'Advanced Enterprise Systems Computing',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 340',   'Introduction to Artificial Intelligence',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 341',   'Object-Oriented System Development',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 350',   'Fundamentals of Information Assurance and Security',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 351',   'Advanced Information Assurance and Applied Cryptography',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 353',   'Web Development Technologies',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 354',   'Advanced Web Application Development',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 356',   'Introduction to Computer Graphics',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 357',   'Tools and Techniques in Information Assurance',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 363',   'Systems Development II',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 367',   'Designing the User Interface',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 372',   'External Data Structures',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 373',   'Wide Area Network Infrastructures',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 375',   'Data Communications',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 376',   'Wireless and Mobile Network Security',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 377',   'Practical Telecommunications Networking',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 378',   'Database Processing',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 379',   'Telecommunications Network Operations and Management',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 380',   'Wireless Communication Systems',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 381',   'Network Design and Analysis',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 382',   'Distributed Systems',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 383',   'Principles of Operating Systems',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 384',   'Computer Architecture',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 388',   'Introduction to Parallel Processing',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 391',   'Directed Project in Information Technology',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 392',   'Enterprise Systems (ES) Integration and App. Development',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 432',   'Systems Analysis and Design',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 450',   'Policy & Administration in Information Assurance & Security',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 463',   'Information Technology Project Management',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 467',   'Human Factors in Information Systems',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 468',   'Software Quality Assurance &Testing',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 477',   'Converged Network Architectures',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 478',   'Advanced Database Management',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 495',   'Information Technology Capstone',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 496',   'Information Technology Strategy and Policy',CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO COURSE (COURSE_CODE,COURSE_NAME,CREATED_TS,LAST_UPDT_TS) VALUES 	('IT 497',   'Introduction to Research Methodology',CURRENT TIMESTAMP, CURRENT TIMESTAMP);

--POPULATE PROFESSOR TABLE
INSERT INTO PROFESSOR (PROF_NAME,ULID,EMPLOYMENT_STATUS,TEACHING_STATUS,CREATED_TS,LAST_UPDT_TS) VALUES	('Califf, Mary Elaine','mecalif ',1,1, CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO PROFESSOR (PROF_NAME,ULID,EMPLOYMENT_STATUS,TEACHING_STATUS,CREATED_TS,LAST_UPDT_TS) VALUES	('Cassels, Lawson','locasse',1,1, CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO PROFESSOR (PROF_NAME,ULID,EMPLOYMENT_STATUS,TEACHING_STATUS,CREATED_TS,LAST_UPDT_TS) VALUES	('Chintalcheru, Naresh','nkchint', 1,1, CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO PROFESSOR (PROF_NAME,ULID,EMPLOYMENT_STATUS,TEACHING_STATUS,CREATED_TS,LAST_UPDT_TS) VALUES	('Gyires, Tibor','tbgyires',1,1, CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO PROFESSOR (PROF_NAME,ULID,EMPLOYMENT_STATUS,TEACHING_STATUS,CREATED_TS,LAST_UPDT_TS) VALUES	('Higgins, Cheri','cheri',1,1, CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO PROFESSOR (PROF_NAME,ULID,EMPLOYMENT_STATUS,TEACHING_STATUS,CREATED_TS,LAST_UPDT_TS) VALUES	('Holbrook, Cathy','cjholbr',1,1, CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO PROFESSOR (PROF_NAME,ULID,EMPLOYMENT_STATUS,TEACHING_STATUS,CREATED_TS,LAST_UPDT_TS) VALUES	('Javadi, Elahe','ejavadi',1,1, CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO PROFESSOR (PROF_NAME,ULID,EMPLOYMENT_STATUS,TEACHING_STATUS,CREATED_TS,LAST_UPDT_TS) VALUES	('Jerome, Sherry','sjerome',1,1, CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO PROFESSOR (PROF_NAME,ULID,EMPLOYMENT_STATUS,TEACHING_STATUS,CREATED_TS,LAST_UPDT_TS) VALUES	('Jia, Ronnie','rjia',1,1, CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO PROFESSOR (PROF_NAME,ULID,EMPLOYMENT_STATUS,TEACHING_STATUS,CREATED_TS,LAST_UPDT_TS) VALUES	('Lance, Rodgers','leroger',1,1, CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO PROFESSOR (PROF_NAME,ULID,EMPLOYMENT_STATUS,TEACHING_STATUS,CREATED_TS,LAST_UPDT_TS) VALUES	('Li, Chung-Chih','cli2',1,1, CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO PROFESSOR (PROF_NAME,ULID,EMPLOYMENT_STATUS,TEACHING_STATUS,CREATED_TS,LAST_UPDT_TS) VALUES	('Lim, Billy','bllim',1,1, CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO PROFESSOR (PROF_NAME,ULID,EMPLOYMENT_STATUS,TEACHING_STATUS,CREATED_TS,LAST_UPDT_TS) VALUES	('Mahatanankoon, Winn','pmahata',1,1, CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO PROFESSOR (PROF_NAME,ULID,EMPLOYMENT_STATUS,TEACHING_STATUS,CREATED_TS,LAST_UPDT_TS) VALUES	('Matsuda, Pat','mpmatsu',1,1, CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO PROFESSOR (PROF_NAME,ULID,EMPLOYMENT_STATUS,TEACHING_STATUS,CREATED_TS,LAST_UPDT_TS) VALUES	('Mitchell, Kim','kkmitch',1,1, CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO PROFESSOR (PROF_NAME,ULID,EMPLOYMENT_STATUS,TEACHING_STATUS,CREATED_TS,LAST_UPDT_TS) VALUES	('Parmenter, Tal','taparme',1,1, CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO PROFESSOR (PROF_NAME,ULID,EMPLOYMENT_STATUS,TEACHING_STATUS,CREATED_TS,LAST_UPDT_TS) VALUES	('Plickebaum, Terry','tlplick',1,1, CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO PROFESSOR (PROF_NAME,ULID,EMPLOYMENT_STATUS,TEACHING_STATUS,CREATED_TS,LAST_UPDT_TS) VALUES	('Qaddour, Jihad','jqaddou',1,1, CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO PROFESSOR (PROF_NAME,ULID,EMPLOYMENT_STATUS,TEACHING_STATUS,CREATED_TS,LAST_UPDT_TS) VALUES	('Sagers, Glenn','gsagers',1,1, CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO PROFESSOR (PROF_NAME,ULID,EMPLOYMENT_STATUS,TEACHING_STATUS,CREATED_TS,LAST_UPDT_TS) VALUES	('Schaefer, Kevin','keschae',1,1, CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO PROFESSOR (PROF_NAME,ULID,EMPLOYMENT_STATUS,TEACHING_STATUS,CREATED_TS,LAST_UPDT_TS) VALUES	('Sikolia, David','dsikoli',1,1, CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO PROFESSOR (PROF_NAME,ULID,EMPLOYMENT_STATUS,TEACHING_STATUS,CREATED_TS,LAST_UPDT_TS) VALUES	('Suh, Kyoungwon','kwsuh',1,1, CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO PROFESSOR (PROF_NAME,ULID,EMPLOYMENT_STATUS,TEACHING_STATUS,CREATED_TS,LAST_UPDT_TS) VALUES	('Tang, Yongning','ytang',1,1, CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO PROFESSOR (PROF_NAME,ULID,EMPLOYMENT_STATUS,TEACHING_STATUS,CREATED_TS,LAST_UPDT_TS) VALUES	('Twitchell, Doug','dtwitch',1,1, CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO PROFESSOR (PROF_NAME,ULID,EMPLOYMENT_STATUS,TEACHING_STATUS,CREATED_TS,LAST_UPDT_TS) VALUES	('Thomas, Todd','tethoma',1,1, CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO PROFESSOR (PROF_NAME,ULID,EMPLOYMENT_STATUS,TEACHING_STATUS,CREATED_TS,LAST_UPDT_TS) VALUES	('Walczynski, Sarah','saskers',1,1, CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO PROFESSOR (PROF_NAME,ULID,EMPLOYMENT_STATUS,TEACHING_STATUS,CREATED_TS,LAST_UPDT_TS) VALUES	('Wallace, Dave','dcwalla',1,1, CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO PROFESSOR (PROF_NAME,ULID,EMPLOYMENT_STATUS,TEACHING_STATUS,CREATED_TS,LAST_UPDT_TS) VALUES	('Walter, Lisa','lkwalte',1,1, CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO PROFESSOR (PROF_NAME,ULID,EMPLOYMENT_STATUS,TEACHING_STATUS,CREATED_TS,LAST_UPDT_TS) VALUES	('Wolf, James','jrwolf',1,1, CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO PROFESSOR (PROF_NAME,ULID,EMPLOYMENT_STATUS,TEACHING_STATUS,CREATED_TS,LAST_UPDT_TS) VALUES	('Zitkus, Doug','dlzitku',1,1, CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO PROFESSOR (PROF_NAME,ULID,EMPLOYMENT_STATUS,TEACHING_STATUS,CREATED_TS,LAST_UPDT_TS) VALUES	('Cancelled','cancelled',1,1, CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO PROFESSOR (PROF_NAME,ULID,EMPLOYMENT_STATUS,TEACHING_STATUS,CREATED_TS,LAST_UPDT_TS) VALUES	('TBD','tbd',1,1, CURRENT TIMESTAMP, CURRENT TIMESTAMP);
INSERT INTO PROFESSOR (PROF_NAME,ULID,EMPLOYMENT_STATUS,TEACHING_STATUS,CREATED_TS,LAST_UPDT_TS) VALUES	('Test Faculty','msabu',1,1, CURRENT TIMESTAMP, CURRENT TIMESTAMP);

--POPULATE USERS TABLE
INSERT INTO USERS (ULID,PASSWORD,ISADMIN,CREATED_TS,LAST_UPDT_TS) VALUES ('admin','admin',1,CURRENT TIMESTAMP,CURRENT TIMESTAMP);
INSERT INTO USERS (ULID,PASSWORD,ISADMIN,CREATED_TS,LAST_UPDT_TS) VALUES ('faculty','faculty',0,CURRENT TIMESTAMP,CURRENT TIMESTAMP);
INSERT INTO USERS (ULID,PASSWORD,ISADMIN,CREATED_TS,LAST_UPDT_TS) VALUES ('msabu','test',0,CURRENT TIMESTAMP,CURRENT TIMESTAMP);

--drop table commands
drop table USERS;
drop table ALL_SCHEDULE;
drop table COURSE;
drop table COURSE_PREFERENCE;
drop table COURSE_Section;
drop table DAY_PREFERENCE;
drop table PROFESSOR;
drop table REVIEW_COMMENT;
drop table ROOM;
drop table SCHEDULE;
drop table TO_DO;